services:
  # MongoDB база данных
  mongodb:
    image: mongo:7.0
    container_name: task_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: taskuser
      MONGO_INITDB_ROOT_PASSWORD: taskpass
      MONGO_INITDB_DATABASE: taskdb
    ports:
      - "27030:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - oktarion_tasks_net
      - oktarion_ngg
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Микросервис на Ktor
  task-service:
    build: .
    container_name: task_microservice
    ports:
      - "${SERVER_PORT:-8046}:${SERVER_PORT:-8046}"
    environment:
      # Database configuration
      MONGODB_CONNECTION_STRING: ${MONGODB_CONNECTION_STRING:-mongodb://taskuser:taskpass@mongodb:27017/taskdb?authSource=admin}
      MONGODB_DATABASE: ${MONGODB_DATABASE:-taskdb}
      DB_MAX_POOL_SIZE: ${DB_MAX_POOL_SIZE:-10}
      
      # Server configuration
      SERVER_PORT: ${SERVER_PORT:-8046}
      SERVER_HOST: ${SERVER_HOST:-0.0.0.0}
      ENVIRONMENT: ${ENVIRONMENT:-production}
      
      # Logging configuration
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      LOG_CORRELATION_ID: ${LOG_CORRELATION_ID:-true}
      
      # Security configuration
      CORS_ENABLED: ${CORS_ENABLED:-true}
      CORS_ORIGINS: ${CORS_ORIGINS:-*}
      RATE_LIMIT_ENABLED: ${RATE_LIMIT_ENABLED:-true}
      RATE_LIMIT_REQUESTS: ${RATE_LIMIT_REQUESTS:-100}
      RATE_LIMIT_WINDOW_MINUTES: ${RATE_LIMIT_WINDOW_MINUTES:-1}
              
      # Pagination configuration
      PAGINATION_DEFAULT_LIMIT: ${PAGINATION_DEFAULT_LIMIT:-50}
      PAGINATION_MAX_LIMIT: ${PAGINATION_MAX_LIMIT:-100}
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - oktarion_tasks_net
      - oktarion_ngg
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${SERVER_PORT:-8046}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mongodb_data:

networks:
  oktarion_tasks_net:
    driver: bridge
  oktarion_ngg:
    external: true
