services:
  # PostgreSQL база данных
  postgres:
    image: postgres:15-alpine
    container_name: event_postgres
    environment:
      POSTGRES_DB: eventdb
      POSTGRES_USER: eventuser
      POSTGRES_PASSWORD: eventpass
    ports:
      - "5437:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - oktarion_events_net
      - oktarion_ngg
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eventuser -d eventdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Микросервис на Ktor
  event-service:
    build: .
    container_name: event_microservice
    ports:
      - "${SERVER_PORT:-8048}:${SERVER_PORT:-8048}"
    environment:
      # Database configuration
      POSTGRES_URL: ${POSTGRES_URL:-jdbc:postgresql://postgres:5432/eventdb}
      POSTGRES_USER: ${POSTGRES_USER:-eventuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-eventpass}
      DB_MAX_POOL_SIZE: ${DB_MAX_POOL_SIZE:-10}
      
      # Server configuration
      SERVER_PORT: ${SERVER_PORT:-8048}
      SERVER_HOST: ${SERVER_HOST:-0.0.0.0}
      ENVIRONMENT: ${ENVIRONMENT:-production}
      
      # Logging configuration
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      LOG_CORRELATION_ID: ${LOG_CORRELATION_ID:-true}
      
      # Security configuration
      CORS_ENABLED: ${CORS_ENABLED:-true}
      CORS_ORIGINS: ${CORS_ORIGINS:-*}
      RATE_LIMIT_ENABLED: ${RATE_LIMIT_ENABLED:-true}
      RATE_LIMIT_REQUESTS: ${RATE_LIMIT_REQUESTS:-100}
      RATE_LIMIT_WINDOW_MINUTES: ${RATE_LIMIT_WINDOW_MINUTES:-1}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - oktarion_events_net
      - oktarion_ngg
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${SERVER_PORT:-8048}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:

networks:
  oktarion_events_net:
    driver: bridge
  oktarion_ngg:
    external: true
